//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ticket_AmandaDEntities : DbContext
    {
        public Ticket_AmandaDEntities()
            : base("name=Ticket_AmandaDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Ticket_Description> Ticket_Description { get; set; }
        public virtual DbSet<Ticket_Message> Ticket_Message { get; set; }
        public virtual DbSet<Ticket_Status> Ticket_Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
