//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_Id { get; set; }
        public System.DateTime Request_Date { get; set; }
        public int Status_Id { get; set; }
        public int Msg_Id { get; set; }
        public int Descript_Id { get; set; }
    
        public virtual Ticket_Description Ticket_Description { get; set; }
        public virtual Ticket_Message Ticket_Message { get; set; }
        public virtual Ticket_Status Ticket_Status { get; set; }
    }
}
